-- ============================================================
-- Global Payroll System — Tax Rules Seed Data
-- Rates are approximate and for demonstration purposes
-- Always verify with a qualified tax professional
-- ============================================================

-- ── US FEDERAL TAX RULES (2024) ──────────────────────────────
-- Federal Income Tax Brackets (Single filer, annual)
INSERT INTO GPS_TAX_RULES (COUNTRY_CODE, TAX_TYPE, TAX_NAME, EMPLOYEE_RATE, EMPLOYER_RATE, INCOME_FROM, INCOME_TO, EFFECTIVE_FROM, APPLIES_TO)
VALUES ('US', 'INCOME', 'US Federal Income Tax 10%', 0.10, 0, 0, 11600, DATE '2024-01-01', 'ALL');

INSERT INTO GPS_TAX_RULES (COUNTRY_CODE, TAX_TYPE, TAX_NAME, EMPLOYEE_RATE, EMPLOYER_RATE, INCOME_FROM, INCOME_TO, EFFECTIVE_FROM, APPLIES_TO)
VALUES ('US', 'INCOME', 'US Federal Income Tax 12%', 0.12, 0, 11601, 47150, DATE '2024-01-01', 'ALL');

INSERT INTO GPS_TAX_RULES (COUNTRY_CODE, TAX_TYPE, TAX_NAME, EMPLOYEE_RATE, EMPLOYER_RATE, INCOME_FROM, INCOME_TO, EFFECTIVE_FROM, APPLIES_TO)
VALUES ('US', 'INCOME', 'US Federal Income Tax 22%', 0.22, 0, 47151, 100525, DATE '2024-01-01', 'ALL');

INSERT INTO GPS_TAX_RULES (COUNTRY_CODE, TAX_TYPE, TAX_NAME, EMPLOYEE_RATE, EMPLOYER_RATE, INCOME_FROM, INCOME_TO, EFFECTIVE_FROM, APPLIES_TO)
VALUES ('US', 'INCOME', 'US Federal Income Tax 24%', 0.24, 0, 100526, 191950, DATE '2024-01-01', 'ALL');

INSERT INTO GPS_TAX_RULES (COUNTRY_CODE, TAX_TYPE, TAX_NAME, EMPLOYEE_RATE, EMPLOYER_RATE, INCOME_FROM, INCOME_TO, EFFECTIVE_FROM, APPLIES_TO)
VALUES ('US', 'INCOME', 'US Federal Income Tax 32%', 0.32, 0, 191951, 243725, DATE '2024-01-01', 'ALL');

INSERT INTO GPS_TAX_RULES (COUNTRY_CODE, TAX_TYPE, TAX_NAME, EMPLOYEE_RATE, EMPLOYER_RATE, INCOME_FROM, INCOME_TO, EFFECTIVE_FROM, APPLIES_TO)
VALUES ('US', 'INCOME', 'US Federal Income Tax 35%', 0.35, 0, 243726, 609350, DATE '2024-01-01', 'ALL');

INSERT INTO GPS_TAX_RULES (COUNTRY_CODE, TAX_TYPE, TAX_NAME, EMPLOYEE_RATE, EMPLOYER_RATE, INCOME_FROM, EFFECTIVE_FROM, APPLIES_TO)
VALUES ('US', 'INCOME', 'US Federal Income Tax 37%', 0.37, 0, 609351, DATE '2024-01-01', 'ALL');

-- US Social Security
INSERT INTO GPS_TAX_RULES (COUNTRY_CODE, TAX_TYPE, TAX_NAME, EMPLOYEE_RATE, EMPLOYER_RATE, INCOME_FROM, INCOME_TO, EFFECTIVE_FROM, APPLIES_TO)
VALUES ('US', 'SOCIAL_SECURITY', 'US Social Security', 0.062, 0.062, 0, 168600, DATE '2024-01-01', 'ALL');

-- US Medicare
INSERT INTO GPS_TAX_RULES (COUNTRY_CODE, TAX_TYPE, TAX_NAME, EMPLOYEE_RATE, EMPLOYER_RATE, INCOME_FROM, EFFECTIVE_FROM, APPLIES_TO)
VALUES ('US', 'MEDICARE', 'US Medicare', 0.0145, 0.0145, 0, DATE '2024-01-01', 'ALL');

-- US Additional Medicare (high earners)
INSERT INTO GPS_TAX_RULES (COUNTRY_CODE, TAX_TYPE, TAX_NAME, EMPLOYEE_RATE, EMPLOYER_RATE, INCOME_FROM, EFFECTIVE_FROM, APPLIES_TO)
VALUES ('US', 'MEDICARE', 'US Additional Medicare', 0.009, 0, 200000, DATE '2024-01-01', 'ALL');

-- ── UK TAX RULES (2024/25) ───────────────────────────────────
-- UK Income Tax
INSERT INTO GPS_TAX_RULES (COUNTRY_CODE, TAX_TYPE, TAX_NAME, EMPLOYEE_RATE, EMPLOYER_RATE, INCOME_FROM, INCOME_TO, EFFECTIVE_FROM, APPLIES_TO)
VALUES ('GB', 'INCOME', 'UK Personal Allowance (0%)', 0.0, 0, 0, 12570, DATE '2024-04-06', 'ALL');

INSERT INTO GPS_TAX_RULES (COUNTRY_CODE, TAX_TYPE, TAX_NAME, EMPLOYEE_RATE, EMPLOYER_RATE, INCOME_FROM, INCOME_TO, EFFECTIVE_FROM, APPLIES_TO)
VALUES ('GB', 'INCOME', 'UK Basic Rate (20%)', 0.20, 0, 12571, 50270, DATE '2024-04-06', 'ALL');

INSERT INTO GPS_TAX_RULES (COUNTRY_CODE, TAX_TYPE, TAX_NAME, EMPLOYEE_RATE, EMPLOYER_RATE, INCOME_FROM, INCOME_TO, EFFECTIVE_FROM, APPLIES_TO)
VALUES ('GB', 'INCOME', 'UK Higher Rate (40%)', 0.40, 0, 50271, 125140, DATE '2024-04-06', 'ALL');

INSERT INTO GPS_TAX_RULES (COUNTRY_CODE, TAX_TYPE, TAX_NAME, EMPLOYEE_RATE, EMPLOYER_RATE, INCOME_FROM, EFFECTIVE_FROM, APPLIES_TO)
VALUES ('GB', 'INCOME', 'UK Additional Rate (45%)', 0.45, 0, 125141, DATE '2024-04-06', 'ALL');

-- UK National Insurance (Class 1 Employee)
INSERT INTO GPS_TAX_RULES (COUNTRY_CODE, TAX_TYPE, TAX_NAME, EMPLOYEE_RATE, EMPLOYER_RATE, INCOME_FROM, INCOME_TO, EFFECTIVE_FROM, APPLIES_TO)
VALUES ('GB', 'NI', 'UK National Insurance 8%', 0.08, 0.138, 12570, 50270, DATE '2024-04-06', 'ALL');

INSERT INTO GPS_TAX_RULES (COUNTRY_CODE, TAX_TYPE, TAX_NAME, EMPLOYEE_RATE, EMPLOYER_RATE, INCOME_FROM, EFFECTIVE_FROM, APPLIES_TO)
VALUES ('GB', 'NI', 'UK National Insurance 2%', 0.02, 0.138, 50271, DATE '2024-04-06', 'ALL');

-- ── INDIA TAX RULES (FY 2024-25, New Regime) ─────────────────
INSERT INTO GPS_TAX_RULES (COUNTRY_CODE, TAX_TYPE, TAX_NAME, EMPLOYEE_RATE, EMPLOYER_RATE, INCOME_FROM, INCOME_TO, EFFECTIVE_FROM, APPLIES_TO)
VALUES ('IN', 'INCOME', 'India Income Tax 0%', 0.0, 0, 0, 300000, DATE '2024-04-01', 'ALL');

INSERT INTO GPS_TAX_RULES (COUNTRY_CODE, TAX_TYPE, TAX_NAME, EMPLOYEE_RATE, EMPLOYER_RATE, INCOME_FROM, INCOME_TO, EFFECTIVE_FROM, APPLIES_TO)
VALUES ('IN', 'INCOME', 'India Income Tax 5%', 0.05, 0, 300001, 600000, DATE '2024-04-01', 'ALL');

INSERT INTO GPS_TAX_RULES (COUNTRY_CODE, TAX_TYPE, TAX_NAME, EMPLOYEE_RATE, EMPLOYER_RATE, INCOME_FROM, INCOME_TO, EFFECTIVE_FROM, APPLIES_TO)
VALUES ('IN', 'INCOME', 'India Income Tax 10%', 0.10, 0, 600001, 900000, DATE '2024-04-01', 'ALL');

INSERT INTO GPS_TAX_RULES (COUNTRY_CODE, TAX_TYPE, TAX_NAME, EMPLOYEE_RATE, EMPLOYER_RATE, INCOME_FROM, INCOME_TO, EFFECTIVE_FROM, APPLIES_TO)
VALUES ('IN', 'INCOME', 'India Income Tax 15%', 0.15, 0, 900001, 1200000, DATE '2024-04-01', 'ALL');

INSERT INTO GPS_TAX_RULES (COUNTRY_CODE, TAX_TYPE, TAX_NAME, EMPLOYEE_RATE, EMPLOYER_RATE, INCOME_FROM, INCOME_TO, EFFECTIVE_FROM, APPLIES_TO)
VALUES ('IN', 'INCOME', 'India Income Tax 20%', 0.20, 0, 1200001, 1500000, DATE '2024-04-01', 'ALL');

INSERT INTO GPS_TAX_RULES (COUNTRY_CODE, TAX_TYPE, TAX_NAME, EMPLOYEE_RATE, EMPLOYER_RATE, INCOME_FROM, EFFECTIVE_FROM, APPLIES_TO)
VALUES ('IN', 'INCOME', 'India Income Tax 30%', 0.30, 0, 1500001, DATE '2024-04-01', 'ALL');

-- India Provident Fund
INSERT INTO GPS_TAX_RULES (COUNTRY_CODE, TAX_TYPE, TAX_NAME, EMPLOYEE_RATE, EMPLOYER_RATE, INCOME_FROM, EFFECTIVE_FROM, APPLIES_TO)
VALUES ('IN', 'PF', 'India Provident Fund', 0.12, 0.12, 0, DATE '2024-04-01', 'FULLTIME');

-- ── AUSTRALIA TAX RULES (FY 2024-25) ────────────────────────
INSERT INTO GPS_TAX_RULES (COUNTRY_CODE, TAX_TYPE, TAX_NAME, EMPLOYEE_RATE, EMPLOYER_RATE, INCOME_FROM, INCOME_TO, EFFECTIVE_FROM, APPLIES_TO)
VALUES ('AU', 'INCOME', 'AU Income Tax 0%', 0.0, 0, 0, 18200, DATE '2024-07-01', 'ALL');

INSERT INTO GPS_TAX_RULES (COUNTRY_CODE, TAX_TYPE, TAX_NAME, EMPLOYEE_RATE, EMPLOYER_RATE, INCOME_FROM, INCOME_TO, EFFECTIVE_FROM, APPLIES_TO)
VALUES ('AU', 'INCOME', 'AU Income Tax 19%', 0.19, 0, 18201, 45000, DATE '2024-07-01', 'ALL');

INSERT INTO GPS_TAX_RULES (COUNTRY_CODE, TAX_TYPE, TAX_NAME, EMPLOYEE_RATE, EMPLOYER_RATE, INCOME_FROM, INCOME_TO, EFFECTIVE_FROM, APPLIES_TO)
VALUES ('AU', 'INCOME', 'AU Income Tax 32.5%', 0.325, 0, 45001, 120000, DATE '2024-07-01', 'ALL');

INSERT INTO GPS_TAX_RULES (COUNTRY_CODE, TAX_TYPE, TAX_NAME, EMPLOYEE_RATE, EMPLOYER_RATE, INCOME_FROM, INCOME_TO, EFFECTIVE_FROM, APPLIES_TO)
VALUES ('AU', 'INCOME', 'AU Income Tax 37%', 0.37, 0, 120001, 180000, DATE '2024-07-01', 'ALL');

INSERT INTO GPS_TAX_RULES (COUNTRY_CODE, TAX_TYPE, TAX_NAME, EMPLOYEE_RATE, EMPLOYER_RATE, INCOME_FROM, EFFECTIVE_FROM, APPLIES_TO)
VALUES ('AU', 'INCOME', 'AU Income Tax 45%', 0.45, 0, 180001, DATE '2024-07-01', 'ALL');

-- Australia Medicare Levy
INSERT INTO GPS_TAX_RULES (COUNTRY_CODE, TAX_TYPE, TAX_NAME, EMPLOYEE_RATE, EMPLOYER_RATE, INCOME_FROM, EFFECTIVE_FROM, APPLIES_TO)
VALUES ('AU', 'MEDICARE', 'AU Medicare Levy', 0.02, 0, 0, DATE '2024-07-01', 'ALL');

-- Australia Superannuation (employer contribution)
INSERT INTO GPS_TAX_RULES (COUNTRY_CODE, TAX_TYPE, TAX_NAME, EMPLOYEE_RATE, EMPLOYER_RATE, INCOME_FROM, EFFECTIVE_FROM, APPLIES_TO)
VALUES ('AU', 'SUPER', 'AU Superannuation', 0.0, 0.115, 0, DATE '2024-07-01', 'FULLTIME');

COMMIT;
