-- ============================================================
-- Global Payroll System — Demo Data Seed
-- Realistic offices and employees across US, GB, IN, AU
-- Run after 001_seed_data.sql and 002_tax_rules.sql
-- ============================================================

-- ── OFFICES ──────────────────────────────────────────────────
INSERT INTO GPS_OFFICES (OFFICE_NAME, COUNTRY_CODE, TIMEZONE, CURRENCY_CODE)
VALUES ('Acme Corp — New York HQ',    'US', 'America/New_York',   'USD');

INSERT INTO GPS_OFFICES (OFFICE_NAME, COUNTRY_CODE, TIMEZONE, CURRENCY_CODE)
VALUES ('Acme Corp — Los Angeles',    'US', 'America/Los_Angeles','USD');

INSERT INTO GPS_OFFICES (OFFICE_NAME, COUNTRY_CODE, TIMEZONE, CURRENCY_CODE)
VALUES ('Acme Corp — London',         'GB', 'Europe/London',      'GBP');

INSERT INTO GPS_OFFICES (OFFICE_NAME, COUNTRY_CODE, TIMEZONE, CURRENCY_CODE)
VALUES ('Acme Corp — Bangalore',      'IN', 'Asia/Kolkata',       'INR');

INSERT INTO GPS_OFFICES (OFFICE_NAME, COUNTRY_CODE, TIMEZONE, CURRENCY_CODE)
VALUES ('Acme Corp — Mumbai',         'IN', 'Asia/Kolkata',       'INR');

INSERT INTO GPS_OFFICES (OFFICE_NAME, COUNTRY_CODE, TIMEZONE, CURRENCY_CODE)
VALUES ('Acme Corp — Sydney',         'AU', 'Australia/Sydney',   'AUD');

INSERT INTO GPS_OFFICES (OFFICE_NAME, COUNTRY_CODE, TIMEZONE, CURRENCY_CODE)
VALUES ('Acme Corp — Melbourne',      'AU', 'Australia/Melbourne','AUD');

-- ── EMPLOYEES ────────────────────────────────────────────────
-- US New York — Full-time salaried
INSERT INTO GPS_EMPLOYEES (EXTERNAL_ID, FIRST_NAME, LAST_NAME, EMAIL, TYPE_CODE, OFFICE_ID, BASE_SALARY, CURRENCY_CODE, HIRE_DATE, KRONOS_ID)
VALUES ('EMP001', 'James',   'Carter',   'jcarter@acme.com',   'FULLTIME', 1, 95000,  'USD', DATE '2019-03-15', 'KRN001');

INSERT INTO GPS_EMPLOYEES (EXTERNAL_ID, FIRST_NAME, LAST_NAME, EMAIL, TYPE_CODE, OFFICE_ID, BASE_SALARY, CURRENCY_CODE, HIRE_DATE, KRONOS_ID)
VALUES ('EMP009', 'Sofia',   'Martinez', 'smartinez@acme.com', 'FULLTIME', 2, 110000, 'USD', DATE '2017-04-22', 'KRN009');

-- US New York — Hourly
INSERT INTO GPS_EMPLOYEES (EXTERNAL_ID, FIRST_NAME, LAST_NAME, EMAIL, TYPE_CODE, OFFICE_ID, HOURLY_RATE, CURRENCY_CODE, HIRE_DATE, KRONOS_ID)
VALUES ('EMP005', 'Marcus',  'Williams', 'mwilliams@acme.com', 'HOURLY',   1, 28.0,   'USD', DATE '2022-05-14', 'KRN005');

-- UK London — Full-time salaried
INSERT INTO GPS_EMPLOYEES (EXTERNAL_ID, FIRST_NAME, LAST_NAME, EMAIL, TYPE_CODE, OFFICE_ID, BASE_SALARY, CURRENCY_CODE, HIRE_DATE, KRONOS_ID)
VALUES ('EMP003', 'Oliver',  'Bennett',  'obennett@acme.com',  'FULLTIME', 3, 65000,  'GBP', DATE '2018-11-20', 'KRN003');

-- UK London — Part-time
INSERT INTO GPS_EMPLOYEES (EXTERNAL_ID, FIRST_NAME, LAST_NAME, EMAIL, TYPE_CODE, OFFICE_ID, HOURLY_RATE, CURRENCY_CODE, HIRE_DATE, KRONOS_ID)
VALUES ('EMP007', 'Emma',    'Wilson',   'ewilson@acme.com',   'PARTTIME', 3, 18.0,   'GBP', DATE '2022-09-05', 'KRN007');

-- India Bangalore — Full-time salaried
INSERT INTO GPS_EMPLOYEES (EXTERNAL_ID, FIRST_NAME, LAST_NAME, EMAIL, TYPE_CODE, OFFICE_ID, BASE_SALARY, CURRENCY_CODE, HIRE_DATE, KRONOS_ID)
VALUES ('EMP002', 'Priya',   'Sharma',   'psharma@acme.com',   'FULLTIME', 4, 1800000,'INR', DATE '2020-07-01', 'KRN002');

-- India Mumbai — Hourly
INSERT INTO GPS_EMPLOYEES (EXTERNAL_ID, FIRST_NAME, LAST_NAME, EMAIL, TYPE_CODE, OFFICE_ID, HOURLY_RATE, CURRENCY_CODE, HIRE_DATE, KRONOS_ID)
VALUES ('EMP006', 'Aisha',   'Patel',    'apatel@acme.com',    'HOURLY',   5, 450.0,  'INR', DATE '2023-01-09', 'KRN006');

-- India Delhi — Contractor
INSERT INTO GPS_EMPLOYEES (EXTERNAL_ID, FIRST_NAME, LAST_NAME, EMAIL, TYPE_CODE, OFFICE_ID, BASE_SALARY, CURRENCY_CODE, HIRE_DATE, KRONOS_ID)
VALUES ('EMP010', 'Raj',     'Kumar',    'rkumar@acme.com',    'CONTRACT', 4, 2400000,'INR', DATE '2023-08-01', 'KRN010');

-- Australia Sydney — Full-time salaried
INSERT INTO GPS_EMPLOYEES (EXTERNAL_ID, FIRST_NAME, LAST_NAME, EMAIL, TYPE_CODE, OFFICE_ID, BASE_SALARY, CURRENCY_CODE, HIRE_DATE, KRONOS_ID)
VALUES ('EMP004', 'Chloe',   'Thompson', 'cthompson@acme.com', 'FULLTIME', 6, 95000,  'AUD', DATE '2021-02-08', 'KRN004');

-- Australia Melbourne — Hourly
INSERT INTO GPS_EMPLOYEES (EXTERNAL_ID, FIRST_NAME, LAST_NAME, EMAIL, TYPE_CODE, OFFICE_ID, HOURLY_RATE, CURRENCY_CODE, HIRE_DATE, KRONOS_ID)
VALUES ('EMP008', 'Liam',    'Johnson',  'ljohnson@acme.com',  'HOURLY',   7, 35.0,   'AUD', DATE '2021-06-30', 'KRN008');

-- ── EMPLOYEE DEDUCTIONS ───────────────────────────────────────
-- James Carter (EMP001) — 401k + Health
INSERT INTO GPS_EMPLOYEE_DEDUCTIONS (EMPLOYEE_ID, DEDUCTION_CODE, PERCENTAGE, EFFECTIVE_FROM)
VALUES (1, '401K', 0.06, DATE '2019-03-15');
INSERT INTO GPS_EMPLOYEE_DEDUCTIONS (EMPLOYEE_ID, DEDUCTION_CODE, AMOUNT, EFFECTIVE_FROM)
VALUES (1, 'HEALTH_INS', 250, DATE '2019-03-15');

-- Oliver Bennett (EMP003) — UK Pension
INSERT INTO GPS_EMPLOYEE_DEDUCTIONS (EMPLOYEE_ID, DEDUCTION_CODE, PERCENTAGE, EFFECTIVE_FROM)
VALUES (3, 'PENSION_UK', 0.05, DATE '2018-11-20');

-- Priya Sharma (EMP002) — India PF
INSERT INTO GPS_EMPLOYEE_DEDUCTIONS (EMPLOYEE_ID, DEDUCTION_CODE, PERCENTAGE, EFFECTIVE_FROM)
VALUES (2, 'PF_INDIA', 0.12, DATE '2020-07-01');

-- Chloe Thompson (EMP004) — Australia Super
INSERT INTO GPS_EMPLOYEE_DEDUCTIONS (EMPLOYEE_ID, DEDUCTION_CODE, PERCENTAGE, EFFECTIVE_FROM)
VALUES (4, 'SUPER_AU', 0.115, DATE '2021-02-08');

-- Sofia Martinez (EMP009) — 401k
INSERT INTO GPS_EMPLOYEE_DEDUCTIONS (EMPLOYEE_ID, DEDUCTION_CODE, PERCENTAGE, EFFECTIVE_FROM)
VALUES (9, '401K', 0.08, DATE '2017-04-22');

-- ── PAYROLL RUN (November 2024) ───────────────────────────────
INSERT INTO GPS_PAYROLL_RUNS (OFFICE_ID, PAY_PERIOD_START, PAY_PERIOD_END, PAY_DATE, STATUS, CURRENCY_CODE, RUN_BY)
VALUES (1, DATE '2024-11-01', DATE '2024-11-30', DATE '2024-11-30', 'COMPLETE', 'USD', 'SYSTEM');

INSERT INTO GPS_PAYROLL_RUNS (OFFICE_ID, PAY_PERIOD_START, PAY_PERIOD_END, PAY_DATE, STATUS, CURRENCY_CODE, RUN_BY)
VALUES (3, DATE '2024-11-01', DATE '2024-11-30', DATE '2024-11-30', 'COMPLETE', 'GBP', 'SYSTEM');

INSERT INTO GPS_PAYROLL_RUNS (OFFICE_ID, PAY_PERIOD_START, PAY_PERIOD_END, PAY_DATE, STATUS, CURRENCY_CODE, RUN_BY)
VALUES (4, DATE '2024-11-01', DATE '2024-11-30', DATE '2024-11-30', 'COMPLETE', 'INR', 'SYSTEM');

INSERT INTO GPS_PAYROLL_RUNS (OFFICE_ID, PAY_PERIOD_START, PAY_PERIOD_END, PAY_DATE, STATUS, CURRENCY_CODE, RUN_BY)
VALUES (6, DATE '2024-11-01', DATE '2024-11-30', DATE '2024-11-30', 'COMPLETE', 'AUD', 'SYSTEM');

-- ── LEAVE BALANCES (2024) ─────────────────────────────────────
-- James Carter
INSERT INTO GPS_LEAVE_BALANCES (EMPLOYEE_ID, LEAVE_CODE, YEAR, ENTITLED_DAYS, TAKEN_DAYS)
VALUES (1, 'ANNUAL', 2024, 15, 5);
INSERT INTO GPS_LEAVE_BALANCES (EMPLOYEE_ID, LEAVE_CODE, YEAR, ENTITLED_DAYS, TAKEN_DAYS)
VALUES (1, 'SICK',   2024, 10, 1);

-- Oliver Bennett
INSERT INTO GPS_LEAVE_BALANCES (EMPLOYEE_ID, LEAVE_CODE, YEAR, ENTITLED_DAYS, TAKEN_DAYS)
VALUES (3, 'ANNUAL', 2024, 28, 10);
INSERT INTO GPS_LEAVE_BALANCES (EMPLOYEE_ID, LEAVE_CODE, YEAR, ENTITLED_DAYS, TAKEN_DAYS)
VALUES (3, 'SICK',   2024, 28, 1);

-- Priya Sharma
INSERT INTO GPS_LEAVE_BALANCES (EMPLOYEE_ID, LEAVE_CODE, YEAR, ENTITLED_DAYS, TAKEN_DAYS)
VALUES (2, 'ANNUAL', 2024, 21, 3);
INSERT INTO GPS_LEAVE_BALANCES (EMPLOYEE_ID, LEAVE_CODE, YEAR, ENTITLED_DAYS, TAKEN_DAYS)
VALUES (2, 'SICK',   2024, 12, 0);

-- Chloe Thompson
INSERT INTO GPS_LEAVE_BALANCES (EMPLOYEE_ID, LEAVE_CODE, YEAR, ENTITLED_DAYS, TAKEN_DAYS)
VALUES (4, 'ANNUAL', 2024, 20, 5);
INSERT INTO GPS_LEAVE_BALANCES (EMPLOYEE_ID, LEAVE_CODE, YEAR, ENTITLED_DAYS, TAKEN_DAYS)
VALUES (4, 'SICK',   2024, 10, 2);

-- ── LEAVE REQUESTS ────────────────────────────────────────────
INSERT INTO GPS_LEAVE_REQUESTS (EMPLOYEE_ID, LEAVE_CODE, START_DATE, END_DATE, DAYS_REQUESTED, STATUS, NOTES)
VALUES (1, 'ANNUAL', DATE '2024-12-23', DATE '2024-12-27', 3, 'APPROVED', 'Christmas break');

INSERT INTO GPS_LEAVE_REQUESTS (EMPLOYEE_ID, LEAVE_CODE, START_DATE, END_DATE, DAYS_REQUESTED, STATUS, NOTES)
VALUES (1, 'SICK',   DATE '2024-10-15', DATE '2024-10-15', 1, 'APPROVED', 'Unwell');

INSERT INTO GPS_LEAVE_REQUESTS (EMPLOYEE_ID, LEAVE_CODE, START_DATE, END_DATE, DAYS_REQUESTED, STATUS, NOTES)
VALUES (3, 'ANNUAL', DATE '2024-08-05', DATE '2024-08-16', 10, 'APPROVED', 'Summer holiday');

INSERT INTO GPS_LEAVE_REQUESTS (EMPLOYEE_ID, LEAVE_CODE, START_DATE, END_DATE, DAYS_REQUESTED, STATUS, NOTES)
VALUES (2, 'ANNUAL', DATE '2024-11-01', DATE '2024-11-05', 3, 'REJECTED', 'Diwali - payroll period, please rebook');

-- ── FX RATES (Nov 2024 approx) ────────────────────────────────
INSERT INTO GPS_FX_RATES (FROM_CURRENCY, TO_CURRENCY, RATE, RATE_DATE)
VALUES ('GBP', 'USD', 1.2650, DATE '2024-11-01');
INSERT INTO GPS_FX_RATES (FROM_CURRENCY, TO_CURRENCY, RATE, RATE_DATE)
VALUES ('INR', 'USD', 0.01197, DATE '2024-11-01');
INSERT INTO GPS_FX_RATES (FROM_CURRENCY, TO_CURRENCY, RATE, RATE_DATE)
VALUES ('AUD', 'USD', 0.6530, DATE '2024-11-01');
INSERT INTO GPS_FX_RATES (FROM_CURRENCY, TO_CURRENCY, RATE, RATE_DATE)
VALUES ('USD', 'GBP', 0.7905, DATE '2024-11-01');
INSERT INTO GPS_FX_RATES (FROM_CURRENCY, TO_CURRENCY, RATE, RATE_DATE)
VALUES ('USD', 'INR', 83.52, DATE '2024-11-01');
INSERT INTO GPS_FX_RATES (FROM_CURRENCY, TO_CURRENCY, RATE, RATE_DATE)
VALUES ('USD', 'AUD', 1.5314, DATE '2024-11-01');

COMMIT;
