-- ============================================================
-- Global Payroll System — Oracle Schema
-- Phase 1: Core tables
-- Run order: execute this file top to bottom
-- ============================================================


-- ── COUNTRIES ────────────────────────────────────────────────
CREATE TABLE GPS_COUNTRIES (
    COUNTRY_CODE        VARCHAR2(3)     NOT NULL,   -- ISO 3166-1 alpha-2 e.g. US, GB, IN
    COUNTRY_NAME        VARCHAR2(100)   NOT NULL,
    CURRENCY_CODE       VARCHAR2(3)     NOT NULL,   -- ISO 4217 e.g. USD, GBP, INR
    FISCAL_YEAR_START   VARCHAR2(5)     NOT NULL,   -- MM-DD e.g. 01-01 or 04-06 (UK)
    PAY_FREQUENCY       VARCHAR2(20)    NOT NULL,   -- MONTHLY | BIWEEKLY | WEEKLY
    ACTIVE              CHAR(1)         DEFAULT 'Y' NOT NULL,
    CREATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_GPS_COUNTRIES PRIMARY KEY (COUNTRY_CODE)
);

-- ── STATES / PROVINCES ───────────────────────────────────────
CREATE TABLE GPS_STATES (
    STATE_ID            NUMBER          GENERATED ALWAYS AS IDENTITY,
    COUNTRY_CODE        VARCHAR2(3)     NOT NULL,
    STATE_CODE          VARCHAR2(10)    NOT NULL,   -- e.g. CA, NY, ENG
    STATE_NAME          VARCHAR2(100)   NOT NULL,
    HAS_STATE_TAX       CHAR(1)         DEFAULT 'N' NOT NULL,
    ACTIVE              CHAR(1)         DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_GPS_STATES PRIMARY KEY (STATE_ID),
    CONSTRAINT UK_GPS_STATES UNIQUE (COUNTRY_CODE, STATE_CODE),
    CONSTRAINT FK_GPS_STATES_COUNTRY FOREIGN KEY (COUNTRY_CODE)
        REFERENCES GPS_COUNTRIES (COUNTRY_CODE)
);

-- ── CITIES ───────────────────────────────────────────────────
CREATE TABLE GPS_CITIES (
    CITY_ID             NUMBER          GENERATED ALWAYS AS IDENTITY,
    STATE_ID            NUMBER          NOT NULL,
    CITY_NAME           VARCHAR2(100)   NOT NULL,
    HAS_CITY_TAX        CHAR(1)         DEFAULT 'N' NOT NULL,
    ACTIVE              CHAR(1)         DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_GPS_CITIES PRIMARY KEY (CITY_ID),
    CONSTRAINT FK_GPS_CITIES_STATE FOREIGN KEY (STATE_ID)
        REFERENCES GPS_STATES (STATE_ID)
);

-- ── EMPLOYEE TYPES ───────────────────────────────────────────
CREATE TABLE GPS_EMPLOYEE_TYPES (
    TYPE_CODE           VARCHAR2(20)    NOT NULL,   -- FULLTIME | HOURLY | PARTTIME | CONTRACT
    TYPE_NAME           VARCHAR2(100)   NOT NULL,
    IS_SALARIED         CHAR(1)         NOT NULL,   -- Y = fixed salary, N = hourly rate
    HAS_BENEFITS        CHAR(1)         DEFAULT 'Y' NOT NULL,
    HAS_OVERTIME        CHAR(1)         DEFAULT 'N' NOT NULL,
    DESCRIPTION         VARCHAR2(500),
    ACTIVE              CHAR(1)         DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_GPS_EMPLOYEE_TYPES PRIMARY KEY (TYPE_CODE)
);

-- ── OFFICES ──────────────────────────────────────────────────
CREATE TABLE GPS_OFFICES (
    OFFICE_ID           NUMBER          GENERATED ALWAYS AS IDENTITY,
    OFFICE_NAME         VARCHAR2(200)   NOT NULL,
    COUNTRY_CODE        VARCHAR2(3)     NOT NULL,
    STATE_ID            NUMBER,
    CITY_ID             NUMBER,
    TIMEZONE            VARCHAR2(50)    NOT NULL,   -- IANA tz e.g. America/New_York
    CURRENCY_CODE       VARCHAR2(3)     NOT NULL,
    ACTIVE              CHAR(1)         DEFAULT 'Y' NOT NULL,
    CREATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_GPS_OFFICES PRIMARY KEY (OFFICE_ID),
    CONSTRAINT FK_GPS_OFFICES_COUNTRY FOREIGN KEY (COUNTRY_CODE)
        REFERENCES GPS_COUNTRIES (COUNTRY_CODE),
    CONSTRAINT FK_GPS_OFFICES_STATE FOREIGN KEY (STATE_ID)
        REFERENCES GPS_STATES (STATE_ID),
    CONSTRAINT FK_GPS_OFFICES_CITY FOREIGN KEY (CITY_ID)
        REFERENCES GPS_CITIES (CITY_ID)
);

-- ── EMPLOYEES ────────────────────────────────────────────────
CREATE TABLE GPS_EMPLOYEES (
    EMPLOYEE_ID         NUMBER          GENERATED ALWAYS AS IDENTITY,
    EXTERNAL_ID         VARCHAR2(50),               -- Kronos / Oracle HCM ID
    FIRST_NAME          VARCHAR2(100)   NOT NULL,
    LAST_NAME           VARCHAR2(100)   NOT NULL,
    EMAIL               VARCHAR2(200)   NOT NULL,
    TYPE_CODE           VARCHAR2(20)    NOT NULL,
    OFFICE_ID           NUMBER          NOT NULL,
    BASE_SALARY         NUMBER(15,2),               -- Annual for salaried, NULL for hourly
    HOURLY_RATE         NUMBER(10,2),               -- NULL for salaried
    CURRENCY_CODE       VARCHAR2(3)     NOT NULL,
    HIRE_DATE           DATE            NOT NULL,
    TERMINATION_DATE    DATE,
    MANAGER_ID          NUMBER,
    KRONOS_ID           VARCHAR2(50),               -- Kronos employee reference
    ACTIVE              CHAR(1)         DEFAULT 'Y' NOT NULL,
    CREATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_GPS_EMPLOYEES PRIMARY KEY (EMPLOYEE_ID),
    CONSTRAINT UK_GPS_EMPLOYEES_EMAIL UNIQUE (EMAIL),
    CONSTRAINT FK_GPS_EMPLOYEES_TYPE FOREIGN KEY (TYPE_CODE)
        REFERENCES GPS_EMPLOYEE_TYPES (TYPE_CODE),
    CONSTRAINT FK_GPS_EMPLOYEES_OFFICE FOREIGN KEY (OFFICE_ID)
        REFERENCES GPS_OFFICES (OFFICE_ID),
    CONSTRAINT FK_GPS_EMPLOYEES_MGR FOREIGN KEY (MANAGER_ID)
        REFERENCES GPS_EMPLOYEES (EMPLOYEE_ID)
);

-- ── TAX RULES ────────────────────────────────────────────────
CREATE TABLE GPS_TAX_RULES (
    TAX_RULE_ID         NUMBER          GENERATED ALWAYS AS IDENTITY,
    COUNTRY_CODE        VARCHAR2(3)     NOT NULL,
    STATE_ID            NUMBER,                     -- NULL = country-level rule
    CITY_ID             NUMBER,                     -- NULL = not city-specific
    TAX_TYPE            VARCHAR2(50)    NOT NULL,   -- INCOME | SOCIAL_SECURITY | MEDICARE | NI | CPF etc.
    TAX_NAME            VARCHAR2(200)   NOT NULL,
    EMPLOYEE_RATE       NUMBER(7,4)     NOT NULL,   -- % as decimal e.g. 0.12 = 12%
    EMPLOYER_RATE       NUMBER(7,4)     DEFAULT 0 NOT NULL,
    INCOME_FROM         NUMBER(15,2)    DEFAULT 0 NOT NULL,
    INCOME_TO           NUMBER(15,2),               -- NULL = no upper limit
    EFFECTIVE_FROM      DATE            NOT NULL,
    EFFECTIVE_TO        DATE,                       -- NULL = currently active
    APPLIES_TO          VARCHAR2(20)    DEFAULT 'ALL' NOT NULL, -- ALL | FULLTIME | HOURLY etc.
    ACTIVE              CHAR(1)         DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_GPS_TAX_RULES PRIMARY KEY (TAX_RULE_ID),
    CONSTRAINT FK_GPS_TAX_COUNTRY FOREIGN KEY (COUNTRY_CODE)
        REFERENCES GPS_COUNTRIES (COUNTRY_CODE),
    CONSTRAINT FK_GPS_TAX_STATE FOREIGN KEY (STATE_ID)
        REFERENCES GPS_STATES (STATE_ID),
    CONSTRAINT FK_GPS_TAX_CITY FOREIGN KEY (CITY_ID)
        REFERENCES GPS_CITIES (CITY_ID)
);

-- ── DEDUCTION TYPES ──────────────────────────────────────────
CREATE TABLE GPS_DEDUCTION_TYPES (
    DEDUCTION_CODE      VARCHAR2(30)    NOT NULL,
    DEDUCTION_NAME      VARCHAR2(200)   NOT NULL,
    COUNTRY_CODE        VARCHAR2(3),                -- NULL = global
    IS_PRE_TAX          CHAR(1)         DEFAULT 'N' NOT NULL,
    IS_MANDATORY        CHAR(1)         DEFAULT 'N' NOT NULL,
    CALCULATION_METHOD  VARCHAR2(20)    NOT NULL,   -- FIXED | PERCENT | FORMULA
    ACTIVE              CHAR(1)         DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_GPS_DEDUCTION_TYPES PRIMARY KEY (DEDUCTION_CODE)
);

-- ── EMPLOYEE DEDUCTIONS ──────────────────────────────────────
CREATE TABLE GPS_EMPLOYEE_DEDUCTIONS (
    DEDUCTION_ID        NUMBER          GENERATED ALWAYS AS IDENTITY,
    EMPLOYEE_ID         NUMBER          NOT NULL,
    DEDUCTION_CODE      VARCHAR2(30)    NOT NULL,
    AMOUNT              NUMBER(15,2),               -- For FIXED type
    PERCENTAGE          NUMBER(7,4),                -- For PERCENT type
    EFFECTIVE_FROM      DATE            NOT NULL,
    EFFECTIVE_TO        DATE,
    ACTIVE              CHAR(1)         DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_GPS_EMP_DEDUCTIONS PRIMARY KEY (DEDUCTION_ID),
    CONSTRAINT FK_GPS_EMP_DED_EMP FOREIGN KEY (EMPLOYEE_ID)
        REFERENCES GPS_EMPLOYEES (EMPLOYEE_ID),
    CONSTRAINT FK_GPS_EMP_DED_TYPE FOREIGN KEY (DEDUCTION_CODE)
        REFERENCES GPS_DEDUCTION_TYPES (DEDUCTION_CODE)
);

-- ── FX RATES ─────────────────────────────────────────────────
CREATE TABLE GPS_FX_RATES (
    FX_RATE_ID          NUMBER          GENERATED ALWAYS AS IDENTITY,
    FROM_CURRENCY       VARCHAR2(3)     NOT NULL,
    TO_CURRENCY         VARCHAR2(3)     NOT NULL,
    RATE                NUMBER(20,8)    NOT NULL,
    RATE_DATE           DATE            NOT NULL,
    SOURCE              VARCHAR2(50)    DEFAULT 'frankfurter.app' NOT NULL,
    CREATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_GPS_FX_RATES PRIMARY KEY (FX_RATE_ID),
    CONSTRAINT UK_GPS_FX_RATES UNIQUE (FROM_CURRENCY, TO_CURRENCY, RATE_DATE)
);

-- ── PAYROLL RUNS ─────────────────────────────────────────────
CREATE TABLE GPS_PAYROLL_RUNS (
    RUN_ID              NUMBER          GENERATED ALWAYS AS IDENTITY,
    OFFICE_ID           NUMBER          NOT NULL,
    PAY_PERIOD_START    DATE            NOT NULL,
    PAY_PERIOD_END      DATE            NOT NULL,
    PAY_DATE            DATE            NOT NULL,
    STATUS              VARCHAR2(20)    DEFAULT 'DRAFT' NOT NULL, -- DRAFT | PROCESSING | COMPLETE | ERROR
    TOTAL_GROSS         NUMBER(18,2)    DEFAULT 0,
    TOTAL_NET           NUMBER(18,2)    DEFAULT 0,
    TOTAL_TAX           NUMBER(18,2)    DEFAULT 0,
    CURRENCY_CODE       VARCHAR2(3)     NOT NULL,
    RUN_BY              VARCHAR2(100),
    STARTED_AT          TIMESTAMP,
    COMPLETED_AT        TIMESTAMP,
    CREATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_GPS_PAYROLL_RUNS PRIMARY KEY (RUN_ID),
    CONSTRAINT FK_GPS_RUNS_OFFICE FOREIGN KEY (OFFICE_ID)
        REFERENCES GPS_OFFICES (OFFICE_ID)
);

-- ── PAYSLIPS ─────────────────────────────────────────────────
CREATE TABLE GPS_PAYSLIPS (
    PAYSLIP_ID          NUMBER          GENERATED ALWAYS AS IDENTITY,
    RUN_ID              NUMBER          NOT NULL,
    EMPLOYEE_ID         NUMBER          NOT NULL,
    PAY_PERIOD_START    DATE            NOT NULL,
    PAY_PERIOD_END      DATE            NOT NULL,
    GROSS_PAY           NUMBER(15,2)    NOT NULL,
    TOTAL_DEDUCTIONS    NUMBER(15,2)    DEFAULT 0 NOT NULL,
    TOTAL_TAX           NUMBER(15,2)    DEFAULT 0 NOT NULL,
    NET_PAY             NUMBER(15,2)    NOT NULL,
    CURRENCY_CODE       VARCHAR2(3)     NOT NULL,
    BASE_CURRENCY_CODE  VARCHAR2(3),                -- For reporting in HQ currency
    FX_RATE             NUMBER(20,8)    DEFAULT 1,
    NET_PAY_BASE_CCY    NUMBER(15,2),               -- Net pay in base currency
    HOURS_WORKED        NUMBER(7,2),                -- From Kronos
    OVERTIME_HOURS      NUMBER(7,2)     DEFAULT 0,
    PDF_PATH            VARCHAR2(500),              -- File path / S3 key
    STATUS              VARCHAR2(20)    DEFAULT 'GENERATED' NOT NULL,
    CREATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_GPS_PAYSLIPS PRIMARY KEY (PAYSLIP_ID),
    CONSTRAINT FK_GPS_PAYSLIPS_RUN FOREIGN KEY (RUN_ID)
        REFERENCES GPS_PAYROLL_RUNS (RUN_ID),
    CONSTRAINT FK_GPS_PAYSLIPS_EMP FOREIGN KEY (EMPLOYEE_ID)
        REFERENCES GPS_EMPLOYEES (EMPLOYEE_ID)
);

-- ── PAYSLIP LINE ITEMS ───────────────────────────────────────
CREATE TABLE GPS_PAYSLIP_LINES (
    LINE_ID             NUMBER          GENERATED ALWAYS AS IDENTITY,
    PAYSLIP_ID          NUMBER          NOT NULL,
    LINE_TYPE           VARCHAR2(20)    NOT NULL,   -- EARNING | DEDUCTION | TAX
    DESCRIPTION         VARCHAR2(200)   NOT NULL,
    AMOUNT              NUMBER(15,2)    NOT NULL,
    SEQUENCE            NUMBER          DEFAULT 1,
    CONSTRAINT PK_GPS_PAYSLIP_LINES PRIMARY KEY (LINE_ID),
    CONSTRAINT FK_GPS_LINES_PAYSLIP FOREIGN KEY (PAYSLIP_ID)
        REFERENCES GPS_PAYSLIPS (PAYSLIP_ID)
);

-- ── LEAVE TYPES ──────────────────────────────────────────────
CREATE TABLE GPS_LEAVE_TYPES (
    LEAVE_CODE          VARCHAR2(20)    NOT NULL,
    LEAVE_NAME          VARCHAR2(100)   NOT NULL,
    COUNTRY_CODE        VARCHAR2(3),                -- NULL = global
    DAYS_PER_YEAR       NUMBER(5,1)     DEFAULT 0,
    IS_PAID             CHAR(1)         DEFAULT 'Y' NOT NULL,
    CARRIES_OVER        CHAR(1)         DEFAULT 'N' NOT NULL,
    ACTIVE              CHAR(1)         DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_GPS_LEAVE_TYPES PRIMARY KEY (LEAVE_CODE)
);

-- ── LEAVE BALANCES ───────────────────────────────────────────
CREATE TABLE GPS_LEAVE_BALANCES (
    BALANCE_ID          NUMBER          GENERATED ALWAYS AS IDENTITY,
    EMPLOYEE_ID         NUMBER          NOT NULL,
    LEAVE_CODE          VARCHAR2(20)    NOT NULL,
    YEAR                NUMBER(4)       NOT NULL,
    ENTITLED_DAYS       NUMBER(5,1)     NOT NULL,
    TAKEN_DAYS          NUMBER(5,1)     DEFAULT 0 NOT NULL,
    PENDING_DAYS        NUMBER(5,1)     DEFAULT 0 NOT NULL,
    REMAINING_DAYS      NUMBER(5,1)     GENERATED ALWAYS AS (ENTITLED_DAYS - TAKEN_DAYS - PENDING_DAYS) VIRTUAL,
    CONSTRAINT PK_GPS_LEAVE_BALANCES PRIMARY KEY (BALANCE_ID),
    CONSTRAINT UK_GPS_LEAVE_BAL UNIQUE (EMPLOYEE_ID, LEAVE_CODE, YEAR),
    CONSTRAINT FK_GPS_LEAVE_BAL_EMP FOREIGN KEY (EMPLOYEE_ID)
        REFERENCES GPS_EMPLOYEES (EMPLOYEE_ID),
    CONSTRAINT FK_GPS_LEAVE_BAL_TYPE FOREIGN KEY (LEAVE_CODE)
        REFERENCES GPS_LEAVE_TYPES (LEAVE_CODE)
);

-- ── LEAVE REQUESTS ───────────────────────────────────────────
CREATE TABLE GPS_LEAVE_REQUESTS (
    REQUEST_ID          NUMBER          GENERATED ALWAYS AS IDENTITY,
    EMPLOYEE_ID         NUMBER          NOT NULL,
    LEAVE_CODE          VARCHAR2(20)    NOT NULL,
    START_DATE          DATE            NOT NULL,
    END_DATE            DATE            NOT NULL,
    DAYS_REQUESTED      NUMBER(5,1)     NOT NULL,
    STATUS              VARCHAR2(20)    DEFAULT 'PENDING' NOT NULL, -- PENDING | APPROVED | REJECTED
    APPROVED_BY         NUMBER,
    NOTES               VARCHAR2(1000),
    CREATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_GPS_LEAVE_REQUESTS PRIMARY KEY (REQUEST_ID),
    CONSTRAINT FK_GPS_LR_EMP FOREIGN KEY (EMPLOYEE_ID)
        REFERENCES GPS_EMPLOYEES (EMPLOYEE_ID),
    CONSTRAINT FK_GPS_LR_TYPE FOREIGN KEY (LEAVE_CODE)
        REFERENCES GPS_LEAVE_TYPES (LEAVE_CODE),
    CONSTRAINT FK_GPS_LR_MGR FOREIGN KEY (APPROVED_BY)
        REFERENCES GPS_EMPLOYEES (EMPLOYEE_ID)
);

-- ── AUDIT LOG ────────────────────────────────────────────────
CREATE TABLE GPS_AUDIT_LOG (
    LOG_ID              NUMBER          GENERATED ALWAYS AS IDENTITY,
    TABLE_NAME          VARCHAR2(100)   NOT NULL,
    RECORD_ID           VARCHAR2(50)    NOT NULL,
    ACTION              VARCHAR2(10)    NOT NULL,   -- INSERT | UPDATE | DELETE
    CHANGED_BY          VARCHAR2(100),
    CHANGED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    OLD_VALUES          CLOB,                       -- JSON snapshot
    NEW_VALUES          CLOB,                       -- JSON snapshot
    CONSTRAINT PK_GPS_AUDIT_LOG PRIMARY KEY (LOG_ID)
);

-- ── INDEXES ──────────────────────────────────────────────────
CREATE INDEX IDX_GPS_EMP_OFFICE    ON GPS_EMPLOYEES (OFFICE_ID);
CREATE INDEX IDX_GPS_EMP_TYPE      ON GPS_EMPLOYEES (TYPE_CODE);
CREATE INDEX IDX_GPS_EMP_KRONOS    ON GPS_EMPLOYEES (KRONOS_ID);
CREATE INDEX IDX_GPS_TAX_COUNTRY   ON GPS_TAX_RULES (COUNTRY_CODE, EFFECTIVE_FROM);
CREATE INDEX IDX_GPS_PAYSLIP_EMP   ON GPS_PAYSLIPS (EMPLOYEE_ID, PAY_PERIOD_START);
CREATE INDEX IDX_GPS_PAYSLIP_RUN   ON GPS_PAYSLIPS (RUN_ID);
CREATE INDEX IDX_GPS_FX_DATE       ON GPS_FX_RATES (RATE_DATE, FROM_CURRENCY, TO_CURRENCY);
CREATE INDEX IDX_GPS_LEAVE_REQ_EMP ON GPS_LEAVE_REQUESTS (EMPLOYEE_ID, STATUS);
CREATE INDEX IDX_GPS_AUDIT_TABLE   ON GPS_AUDIT_LOG (TABLE_NAME, CHANGED_AT);
